title: 欢迎使用
subtitle: 个人导航站点

# 指定使用的模板文件名，现有页面模板可见templates\pages
template: home

categories:
  - name: 常用网站
    icon: fas fa-star
    sites:
      - name: Linux.do
        url: https://linux.do/
        icon: fab fa-linux
        description: 新的理想型社区
      - name: GitHub
        url: https://www.github.com
        icon: fab fa-github
        description: 代码托管平台

  - name: 学习资源
    icon: fas fa-graduation-cap
    sites:
      - name: 哔哩哔哩
        url: https://www.bilibili.com
        icon: fas fa-play-circle
        description: 视频学习平台

      - name: LeetCode
        url: https://leetcode.cn
        icon: fas fa-code
        description: 算法刷题平台

      - name: 学习通
        url: https://i.chaoxing.com/base?t=1670383247885
        icon: fas fa-book
        description: 学习通

  - name: 常用AI
    icon: fas fa-robot
    sites:
      - name: ChatGPT
        url: https://chat.openai.com
        icon: fas fa-robot
        description: OpenAI

      - name: KIMI
        url: https://kimi.moonshot.cn/
        icon: fas fa-robot
        description: KIMI AI

  - name: 管理面板
    icon: fas fa-cogs
    sites:
      - name: 阿里2h2g
        url: https://8.130.97.54:4915
        icon: fas fa-server
        description: 阿里云2h2g管理面板

      - name: 华为云2g4g
        url: https://123.60.45.109:4915/
        icon: fas fa-server
        description: 华为云2g4g管理面板

      - name: 华为云2h2g
        url: https://1.94.111.243:4915
        icon: fas fa-server
        description: 华为云2h2g管理面板

    
   