title: "我的项目中心"
subtitle: "个人项目精选站点"

template: projects

categories:

  - name: "面板类"
    icon: "fas fa-th-large"
    sites:
      - name: "暂未推出"
        url: "https://www.maxtrnn.top"
        icon: "fas fa-spinner"
        description: "暂未推出"

  - name: "功能类"
    icon: "fas fa-cogs"
    sites:
      - name: "MAX-GPT"
        url: "https://maxgpt.maxtrnn.top/"
        icon: "fas fa-robot"
        description: "MAX搭建的GPT中枢"

  - name: "记录类"
    icon: "fas fa-book"
    sites:
      - name: "MAX-博客"
        url: "https://maxtrnn.top/"
        icon: "fas fa-blog"
        description: "MAX自己的博客"

  - name: "社交"
    icon: "fas fa-users"
    sites:
      - name: "MAX-加入群聊"
        url: "https://qm.qq.com/cgi-bin/qm/qr?authKey=%2FT6n1OfYlIlZn9NZMWvn3WojOj6jM4bFQ0Ol5OcaNki1acriJ8y5fWcErugpOwRq&k=CA4A0v-DHevipsSxRwnx-kCD5CWxLlsL&noverify=0"
        icon: "fab fa-qq"
        description: "加入MAX群聊"
