title: "我的项目中心"
subtitle: "个人项目、开发工具、学习资源和精选站点"

# 指定使用的模板文件名，现有页面模板可见templates\pages
template: projects

categories:
  - name: "学习资源"
    icon: "fas fa-graduation-cap"
    sites:
      - name: "MDN Web Docs"
        url: "https://developer.mozilla.org"
        icon: "fab fa-firefox-browser"
        description: "Web开发完整指南"
      - name: "freeCodeCamp"
        url: "https://www.freecodecamp.org"
        icon: "fab fa-free-code-camp"
        description: "免费编程学习平台"
      - name: "Coursera"
        url: "https://www.coursera.org"
        icon: "fas fa-university"
        description: "全球顶尖在线课程"

  - name: "开发工具"
    icon: "fas fa-tools"
    sites:
      - name: "GitHub"
        url: "https://github.com"
        icon: "fab fa-github"
        description: "代码托管平台"
      - name: "VS Code"
        url: "https://vscode.dev/?vscode-lang=zh-cn"
        icon: "fas fa-code"
        description: "强大的代码编辑器"
      - name: "GitHub Project"
        url: "https://github.com/itmanmax"
        icon: "fab fa-github-alt"
        description: "MAX的Github"
      - name: "GItee Project"
        url: "https://gitee.com/wudimax/projects"
        icon: "fab fa-gitee"
        description: "MAX的Gitee"
      - name: "CodePen"
        url: "https://codepen.io"
        icon: "fab fa-codepen"
        description: "在线web代码编辑器"

  - name: "设计资源"
    icon: "fas fa-palette"
    sites:
      - name: "Dribbble"
        url: "https://dribbble.com"
        icon: "fab fa-dribbble"
        description: "设计师作品展示平台"
      - name: "Figma"
        url: "https://www.figma.com"
        icon: "fab fa-figma"
        description: "协作设计工具"
      - name: "Unsplash"
        url: "https://unsplash.com"
        icon: "fas fa-camera-retro"
        description: "免费高质量图片"

  - name: "个人开发"
    icon: "fas fa-user-astronaut"
    sites:
      - name: "MAX-门户-2"
        url: "https://vercel1.maxtral.fun/"
        icon: "fas fa-pager"
        description: "MAX的门户页面-2"
      - name: "MAX-GPT"
        url: "https://maxgpt.maxtral.fun/"
        icon: "fas fa-robot"
        description: "MAX搭建的GPT中枢"
      - name: "MAX-图床"
        url: "https://pic.maxtral.fun/"
        icon: "fas fa-cloud-upload-alt"
        description: "MAX搭建的图床"
      - name: "MAX-博客"
        url: "https://maxtral.fun/"
        icon: "fas fa-blog"
        description: "MAX自己的博客"
      - name: "MAX-网盘"
        url: "http://cloude.maxtral.fun/"
        icon: "fas fa-hdd"
        description: "MAX搭建的网盘"
      - name: "MAX-状态-1"
        url: "http://nezha.maxtral.fun/"
        icon: "fas fa-server"
        description: "MAX服务器的状态-1"
      - name: "MAX-状态-2"
        url: "https://severstatus.maxtral.fun/"
        icon: "fas fa-network-wired"
        description: "MAX服务器的状态-2"
      - name: "MAX-音乐平台-1"
        url: "https://music.maxtral.fun/"
        icon: "fas fa-music"
        description: "MAX自己搭建的音乐平台-1"
      - name: "MAX-gemini-1"
        url: "https://govercel.maxtral.fun/"
        icon: "fas fa-comments"
        description: "MAX自己搭建gemini交流平台-1"
      - name: "MAX-文件中转-1"
        url: "http://kuaidi.maxtral.fun/#/"
        icon: "fas fa-exchange-alt"
        description: "MAX自己搭建文件中转平台-1"
      - name: "MAX-思源笔记-999"
        url: "http://siyuan.maxtral.fun/"
        icon: "fas fa-book-open"
        description: "MAX自己搭建的思源笔记-999（需要密码）"
      - name: "MAX-账号密码-999"
        url: "http://pt.maxtral.fun/"
        icon: "fas fa-key"
        description: "MAX自己的账号密码平台-999（需要密码）"
      - name: "MAX-Alist-999"
        url: "http://alist.maxtral.fun/@login?redirect=%2F"
        icon: "fas fa-database"
        description: "MAX的Alist平台-999（需要密码）"
      - name: "MAX-加入群聊"
        url: "https://qm.qq.com/cgi-bin/qm/qr?authKey=%2FT6n1OfYlIlZn9NZMWvn3WojOj6jM4bFQ0Ol5OcaNki1acriJ8y5fWcErugpOwRq&k=CA4A0v-DHevipsSxRwnx-kCD5CWxLlsL&noverify=0"
        icon: "fab fa-qq"
        description: "加入MAX群聊"

  - name: "AI助手"
    icon: "fas fa-brain"
    sites:
      - name: "MAX-gemini-1"
        url: "https://govercel.maxtral.fun/"
        icon: "fas fa-comments"
        description: "MAX自己搭建gemini交流平台-1"
      - name: "MAX-GPT"
        url: "https://maxgpt.maxtral.fun/"
        icon: "fas fa-robot"
        description: "MAX搭建的GPT中枢"
      - name: "ChatGPT"
        url: "https://chat.openai.com"
        icon: "fas fa-comment-alt"
        description: "OpenAI聊天助手"
      - name: "Claude"
        url: "https://claude.ai"
        icon: "fas fa-comment-dots"
        description: "Anthropic AI助手"
      - name: "Midjourney"
        url: "https://www.midjourney.com"
        icon: "fas fa-paint-brush"
        description: "AI图像生成"
      - name: "Copilot"
        url: "https://github.com/features/copilot"
        icon: "fab fa-github"
        description: "GitHub代码助手"

  - name: "生产力工具"
    icon: "fas fa-briefcase"
    sites:
      - name: "MAX-网盘"
        url: "http://cloude.maxtral.fun/"
        icon: "fas fa-hdd"
        description: "MAX搭建的网盘"
      - name: "MAX-图床"
        url: "https://pic.maxtral.fun/"
        icon: "fas fa-cloud-upload-alt"
        description: "MAX搭建的图床"
      - name: "Notion"
        url: "https://www.notion.so"
        icon: "fas fa-file-invoice"
        description: "全能笔记和协作工具"
      - name: "Trello"
        url: "https://trello.com"
        icon: "fab fa-trello"
        description: "项目管理工具"
      - name: "Slack"
        url: "https://slack.com"
        icon: "fab fa-slack"
        description: "团队沟通平台"

  - name: "娱乐"
    icon: "fas fa-compact-disc"
    sites:
      - name: "MAX-音乐平台-1"
        url: "https://music.maxtral.fun/"
        icon: "fas fa-music"
        description: "MAX自己搭建的音乐平台-1"
      - name: "Spotify"
        url: "https://www.spotify.com"
        icon: "fab fa-spotify"
        description: "音乐流媒体服务"
      - name: "Netflix"
        url: "https://www.netflix.com"
        icon: "fas fa-tv"
        description: "影视串流平台"
      - name: "今日热榜"
        url: "https://hot.imsyy.top/#/"
        icon: "fas fa-fire"
        description: "今日热榜"
      - name: "YouTube"
        url: "https://www.youtube.com"
        icon: "fab fa-youtube"
        description: "视频分享平台" 