title: "我的项目中心"
subtitle: "个人项目精选站点"

template: projects

categories:

  - name: "面板类"
    icon: "fas fa-th-large"
    sites:
      - name: "MAX-门户-2"
        url: "https://vercel1.maxtral.fun/"
        icon: "fas fa-pager"
        description: "MAX的门户页面-2"
      - name: "MAX-状态-1"
        url: "http://nezha.maxtral.fun/"
        icon: "fas fa-server"
        description: "MAX服务器的状态-1"
      - name: "MAX-状态-2"
        url: "https://severstatus.maxtral.fun/"
        icon: "fas fa-network-wired"
        description: "MAX服务器的状态-2"
      - name: "MAX-Alist-999"
        url: "http://alist.maxtral.fun/@login?redirect=%2F"
        icon: "fas fa-database"
        description: "MAX的Alist平台-999（需要密码）"
      - name: "MAX-网盘"
        url: "http://cloude.maxtral.fun/"
        icon: "fas fa-hdd"
        description: "MAX搭建的网盘"

  - name: "功能类"
    icon: "fas fa-cogs"
    sites:
      - name: "MAX-GPT"
        url: "https://maxgpt.maxtral.fun/"
        icon: "fas fa-robot"
        description: "MAX搭建的GPT中枢"
      - name: "MAX-图床"
        url: "https://pic.maxtral.fun/"
        icon: "fas fa-cloud-upload-alt"
        description: "MAX搭建的图床"
      - name: "MAX-音乐平台-1"
        url: "https://music.maxtral.fun/"
        icon: "fas fa-music"
        description: "MAX自己搭建的音乐平台-1"
      - name: "MAX-gemini-1"
        url: "https://govercel.maxtral.fun/"
        icon: "fas fa-comments"
        description: "MAX自己搭建gemini交流平台-1"
      - name: "MAX-文件中转-1"
        url: "http://kuaidi.maxtral.fun/#/"
        icon: "fas fa-exchange-alt"
        description: "MAX自己搭建文件中转平台-1"

  - name: "学习类"
    icon: "fas fa-book"
    sites:
      - name: "MAX-思源笔记-999"
        url: "http://siyuan.maxtral.fun/"
        icon: "fas fa-book-open"
        description: "MAX自己搭建的思源笔记-999（需要密码）"
      - name: "MAX-博客"
        url: "https://maxtral.fun/"
        icon: "fas fa-blog"
        description: "MAX自己的博客"

  - name: "账号管理"
    icon: "fas fa-user-lock"
    sites:
      - name: "MAX-账号密码-999"
        url: "http://pt.maxtral.fun/"
        icon: "fas fa-key"
        description: "MAX自己的账号密码平台-999（需要密码）"

  - name: "社交"
    icon: "fas fa-users"
    sites:
      - name: "MAX-加入群聊"
        url: "https://qm.qq.com/cgi-bin/qm/qr?authKey=%2FT6n1OfYlIlZn9NZMWvn3WojOj6jM4bFQ0Ol5OcaNki1acriJ8y5fWcErugpOwRq&k=CA4A0v-DHevipsSxRwnx-kCD5CWxLlsL&noverify=0"
        icon: "fab fa-qq"
        description: "加入MAX群聊"
