title: MAX的导航
description: 个人导航站
author: MAXTRNN
favicon: favicon.ico
logo_text: 导航站

fonts:
  title:
    family: Poppins
    weight: 600
    source: google
  subtitle:
    family: Quicksand
    weight: 500
    source: google
  body:
    family: Noto Sans SC
    weight: 400
    source: google
    
profile:
  title: Hello,
  subtitle: Welcome to MAXTRNN Navigation
  description: 导航菜单

social:
  - name: GitHub
    url: https://github.com/itmanmax
    icon: fab fa-github
  - name: TikTok
    url: https://cloudflare.maxtral.fun/H0xalL
    icon: fab fa-tiktok
  - name: X
    url: https://x.com/maxtr2n?s=21
    icon: fab fa-x
  - name: Steam
    url: https://steamcommunity.com/profiles/76561199097239066/
    icon: fab fa-steam 
  - name: QQ
    url: https://cloudflare.maxtral.fun/HWlUGj
    icon: fab fa-qq 